// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: regedit.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegeditClient is the client API for Regedit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegeditClient interface {
	EndPointRegedit(ctx context.Context, in *RegEditRQ, opts ...grpc.CallOption) (*RegEditRS, error)
}

type regeditClient struct {
	cc grpc.ClientConnInterface
}

func NewRegeditClient(cc grpc.ClientConnInterface) RegeditClient {
	return &regeditClient{cc}
}

func (c *regeditClient) EndPointRegedit(ctx context.Context, in *RegEditRQ, opts ...grpc.CallOption) (*RegEditRS, error) {
	out := new(RegEditRS)
	err := c.cc.Invoke(ctx, "/pb.Regedit/EndPointRegedit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegeditServer is the server API for Regedit service.
// All implementations should embed UnimplementedRegeditServer
// for forward compatibility
type RegeditServer interface {
	EndPointRegedit(context.Context, *RegEditRQ) (*RegEditRS, error)
}

// UnimplementedRegeditServer should be embedded to have forward compatible implementations.
type UnimplementedRegeditServer struct {
}

func (UnimplementedRegeditServer) EndPointRegedit(context.Context, *RegEditRQ) (*RegEditRS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndPointRegedit not implemented")
}

// UnsafeRegeditServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegeditServer will
// result in compilation errors.
type UnsafeRegeditServer interface {
	mustEmbedUnimplementedRegeditServer()
}

func RegisterRegeditServer(s grpc.ServiceRegistrar, srv RegeditServer) {
	s.RegisterService(&Regedit_ServiceDesc, srv)
}

func _Regedit_EndPointRegedit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegEditRQ)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegeditServer).EndPointRegedit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Regedit/EndPointRegedit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegeditServer).EndPointRegedit(ctx, req.(*RegEditRQ))
	}
	return interceptor(ctx, in, info, handler)
}

// Regedit_ServiceDesc is the grpc.ServiceDesc for Regedit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Regedit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Regedit",
	HandlerType: (*RegeditServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EndPointRegedit",
			Handler:    _Regedit_EndPointRegedit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "regedit.proto",
}
